config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  resources :accounts
  resources :products
  resources :coupons
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get '/rules',  to: 'pages#rule'
  get '/help',  to: 'pages#help'
  get '/payment',  to: 'pages#payment'
  get '/configuration',  to: 'pages#configuration'
  get '/users/balance', to: 'pages#balance'
  get '/account/pay',   to: 'accounts#pay'
  get '/users/:id',     to: 'pages#user'
  root to: 'products#index'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    has_many :messages
    accepts_nested_attributes_for :messages
    validates  :title, presence: true
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.where('sender_id=? OR reender_id=?', current_user.id, current_user.id)
  end

  # GET /conversations/1
  # GET /conversations/1.json
  def show
    conv = Conversation.find(params['id'])
    
    if (conv.sender_id == current_user.id )|| (conv.reender_id == current_user.id)
      @messages = conv.messages
      @messages.each do |f|
        if f.sender_id == current_user.id
          f.sender = true
        else
          f.resender = true
        end
        f.save
      end
    
    else
      redirect_to conversation_params
    end
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
    @conversation.messages.build
  end

  # GET /conversations/1/edit
  def edit
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:title, :sender_id, :reender_id, messages_attributes: [:text, :conversation_id, :sender_id, :resender_id, :sender, :resender])
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.haml
= form_for @conversation, html: { class: "form form-horizontal conversation" } do |f|
  .form-group
    = f.label 'Тема'
    = f.text_field :title, class: 'form-control', required: true
    = f.error_span(:title)
    = f.text_field :sender_id, class: 'hide', value: current_user.id
    = f.text_field :reender_id, class: 'hide', value: @user.id
  .form-group
    = f.fields_for :messages do |b|
      = b.label "Сообщение"
      = b.text_area :text, class: 'form-control', required: true
      = b.number_field :sender_id, value: current_user.id, class: 'hide'
      = b.number_field :resender_id, value: @user.id, class: 'hide'
      = b.check_box :sender, checked: true, class: 'hide'
  .form-group
    = f.submit "Начать диалог",class: 'btn btn-primary'
  

app/views/conversations/edit.html.haml
- model_class = Conversation
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/conversations/index.html.haml
- model_class = Conversation
.page-header
  %h1 Диалоги
- if @conversations.count > 0
  %table.table.table-striped
    %thead
      %tr
        %th Название
        %th Дата
        %th Сообщение
    %tbody
      - @conversations.each do |conversation|
        %tr
          %td= link_to conversation.title, conversation_path(conversation)
          %td= conversation.created_at.strftime('%d.%m.%Y')
          %td 
            #{get_message(conversation.id)}
-else
  %h4 Диалогов нет

app/views/conversations/new.html.haml
- model_class = Conversation
.page-header
  %h1 Новый диалог
  
= render :partial => "conversations/form"

app/views/conversations/show.html.haml
- model_class = Conversation
.page-header
  %h1
    = @conversation.title
  %span.text-right= @conversation.created_at.strftime('%d.%m.%Y')

.row
  #chat.chat
    - @messages.each do |f|
      -if f.sender_id == current_user.id
        %p.text-right
          %b #{current_user.email.split('@')[0].gsub(/\b./, &:upcase)}: #{f.created_at.strftime('%d.%m.%Y %H:%M')}
          %br/
          = f.text
          %hr.ch
      -else 
        %p.text-left
          %b #{User.find(f.sender_id).email.split('@')[0].gsub(/\b./, &:upcase)}: #{f.created_at.strftime('%d.%m.%Y %H:%M')}
          %br/
          = f.text
          %hr.ch
  .col-md-12
    = form_for @conversation, html: { class: "form conversation" } do |f|
      = f.fields_for @conversation.messages.build, html: { class: "form message" } do |b|
        .form-group.col-md-10
          = b.text_area :text, class: 'form-control', required: true, name: 'conversation[messages_attributes][0][text]', placeholder: 'Введите сообщение...'
          = b.number_field :sender_id, value: current_user.id, class: 'hide', name: 'conversation[messages_attributes][0][sender_id]'
          = b.number_field :resender_id, value: @conversation.reender_id, class: 'hide', name: 'conversation[messages_attributes][0][resender_id]'
          = b.check_box :sender, checked: true, class: 'hide', name: 'conversation[messages_attributes][0][sender]'
        .form-group.col-md-2
          = b.submit "Отправить",class: 'btn btn-primary'


:javascript
  var chat = document.getElementById("chat")
  chat.scrollTop = chat.scrollHeight;