config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  resources :accounts
  resources :products
  resources :coupons
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get '/rules',  to: 'pages#rule'
  get '/help',  to: 'pages#help'
  get '/payment',  to: 'pages#payment'
  get '/configuration',  to: 'pages#configuration'
  get '/users/balance', to: 'pages#balance'
  get '/account/pay',   to: 'accounts#pay'
  get '/users/:id',     to: 'pages#user'
  root to: 'products#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new
      if user.admin?
        can :manage, :all
      elsif user.buyer?
        can :read, Product
        can :manage, Account, buyer_id: user.id
        can :update, Account, buyer_id: nil        
        can :manage, User, id: user.id
        can :manage, Message.where('sender_id=? OR resender_id=?', user.id, user.id)
        can :manage, Conversation.where('sender_id=? OR reender_id=?', user.id, user.id)
      elsif user.seller?
        can :manage, Product
        can :manage, Account, seller_id: user.id    
        can :manage, User, id: user.id
        can :manage, Message.where('sender_id=? OR resender_id=?', user.id, user.id)
        can :manage, Conversation.where('sender_id=? OR reender_id=?', user.id, user.id)  
      end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :product
  belongs_to :buyer, class_name: "User", foreign_key:"buyer_id", optional: true
  belongs_to :seller, class_name: "User", foreign_key:"seller_id", optional: true
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/buyer.rb
class Buyer < User
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    has_many :messages
    accepts_nested_attributes_for :messages
    validates  :title, presence: true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
	validates :code, presence: true, uniqueness: true
	validates :value, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  validates  :text, presence: true
  belongs_to :conversation
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, presence: true
  validates :descriptoin, presence: true
  mount_uploader :photo, PhotoUploader
  serialize :photo, JSON
  has_many :accounts
end

app/models/seller.rb
class Seller < User
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :accounts

  after_create :default_type
  
  def default_type
    self.type = 'Buyer'
  end

  def admin?
  	type == 'Admin'
  end

  def seller?
  	type == 'Seller'
  end

  def buyer?
  	type == 'Buyer'
  end
  
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
    
  def index
    @coupons = Coupon.all
  end

  def show
  end

  def new
    @coupon = Coupon.new
  end

  def edit
  end

  def create
    unless params['coupon']['pcs'].nil?
      pcs = params['coupon']['pcs']
      value = params['coupon']['value']
      (1..pcs.to_i).each do |f|
        Coupon.create(code: [*('a'..'z'),*('0'..'9'),*('A'..'Z')].shuffle[0,10].join, value: value, active: true)
      end      
    end
    respond_to do |format|
      if @coupon.save
        format.html { redirect_to '/configuration', notice: 'Coupon was successfully created.' }
        format.json { render '/configuration', status: :created, location: '/configuration' }
      else
        format.html { redirect_to '/configuration' }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @coupon.update(coupon_params)
        format.html { redirect_to @coupon, notice: 'Coupon was successfully updated.' }
        format.json { render :show, status: :ok, location: @coupon }
      else
        format.html { render :edit }
        format.json { render json: @coupon.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @coupon.destroy
    respond_to do |format|
      format.html { redirect_to coupons_url, notice: 'Coupon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    def coupon_params
      params.require(:coupon).permit(:code, :value, :active)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def rule
    @page = Page.find_by(url: 'rules')
  end
  def payment
    @page = Page.find_by(url: 'payment')
  end
  def help
    @page = Page.find_by(url: 'help')
  end
  def user
    @user = User.find(params[:id])
  end
  def balance
    unless params['code'].nil?
      coupon = Coupon.find_by(code: params['code'])
      if coupon && coupon.active
        coupon.active = false
        coupon.save
        current_user.balance += coupon.value
        current_user.save
        flash[:success] = "Купон активирован!"
      else
        flash[:alert] = "Код купона не верен!"
      end
      redirect_to '/users/balance/'
    end
  end

  def configuration
    redirect_to '/' unless (current_user && current_user.admin?)
    @coupon = Coupon.new
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def message_count
        Message.where(sender_id: current_user.id).where(sender: false).count + Message.where(resender_id: current_user.id).where(resender: false).count
    end

    def get_message(id)
        con = Conversation.find(id)
        if con.sender_id == current_user.id
            "#{con.messages.where(sender_id: current_user.id).where(sender: false).count} / #{con.messages.count}"
        elsif con.reender_id == current_user.id
            "#{con.messages.where('resender_id=? AND resender=?', current_user.id, false).count} / #{con.messages.count}"
        end
    end

    def sender_account_sold(id)
        Account.where(seller_id: @user.id).where(buyer_id: nil).count
    end

    def sender_account_all(id)
        Account.where(seller_id: @user.id).count
    end

    def buyer_account id
        Account.where(buyer_id: @user.id).count
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Gameshop"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"


  %body
    .navbar.navbar-default.navbar-static-top.navgame
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        %a.navbar-brand(href="/")
          %span.logo
            %img.logo{:src => "/img/logo.png", :alt => ""}
            Gameshop
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            -if user_signed_in?
              %li
                = link_to '/' do
                  %span.glyphicon.glyphicon-star
                  Все Игры
            -if user_signed_in? && (current_user.seller? || current_user.admin?)
              %li
                =link_to new_product_path do
                  %span.glyphicon.glyphicon-plus
                  Добавить Игру
            -if user_signed_in?
              %li
                =link_to accounts_path do
                  %span.glyphicon.glyphicon-gift
                  Аккаунты
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                  %span.glyphicon.glyphicon-question-sign
                  Помощь
                  %span.caret
                  %ul.dropdown-menu
                    %li
                      =link_to "Правила", '/rules'
                    %li
                      =link_to "Инструкция по установке", '/help'
                    %li
                      =link_to "Пополнение баланса", '/payment'
          %ul.nav.navbar-nav.navbar-right
            -if user_signed_in?
              -if current_user.admin?
                %li
                  %a{:href => "/admin"}
                    %span.glyphicon.glyphicon-signal 
                    Админка
                %li
                  %a{:href => "/configuration"}
                    %span.glyphicon.glyphicon-bookmark
                    Купоны
              %li
                %a{:href => "#{edit_user_registration_path}"}
                  %span.glyphicon.glyphicon-user
                  #{current_user.email.split('@')[0].gsub(/\b./, &:upcase)}
              %li
                %a(href="#{users_balance_path}")
                  #{current_user.balance}
                  %span.rub ₽	
              %li
                %a(href="#{conversations_path}")
                  %span.glyphicon.glyphicon-envelope
                  = message_count
              %li
                = link_to destroy_user_session_path, method: :delete do
                  %span.glyphicon.glyphicon-log-out 
                  Выход
            -else
              %li
                = link_to new_user_registration_path do
                  %span.glyphicon.glyphicon-user 
                  Регистрация
              %li
                = link_to new_user_session_path do
                  %span.glyphicon.glyphicon-log-in 
                  Вход

    .container
      .row.page
        .col-md-10.col-md-offset-1
          = bootstrap_flash
          = yield
        

    #footer
      .container
        .wrapper.text-center
          %span
            GameShop Copyright © 2018
          .clearfix

app/views/pages/balance.html.haml
.row
  %h2 Пополнить баланс
  %br/
  = form_tag("/users/balance", method: "get", class:'form-inline') do
    .form-group
      = text_field_tag 'code', nil, class: 'form-control', placeholder: 'Код купона'
      = submit_tag("Активировать", class: 'btn btn-primary')

app/views/pages/configuration.html.haml
.row
  .col-md-12
    .panel-body
      %h3 Создание купонов
      = form_for @coupon do |f|
        .form-group
          %label Сумма
          = f.number_field :value, class: "form-control"
        .form-group
          %label Количество
          %input#coupon_pcs.form-control{:name => "coupon[pcs]", :type => "number"}/
        %br/
        .form-group
          .action
            = f.submit 'Добавить', class: 'btn btn-primary'
  .col-md-12
    %table#coupons.display.table.table-striped
      %thead 
        %tr
          %th Код
          %th Цена
          %th Статус
      %tbody
        -Coupon.all.each do |a|
          %tr
            %td= a.code
            %td= a.value
            %td
              -if a.active?
                Активный
              -else
                Использован
:javascript
  $('#coupons').DataTable({
    "language":{
      "processing": "Подождите...",
      "search": "Поиск:",
      "lengthMenu": "Показать _MENU_ записей",
      "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
      "infoEmpty": "Записи с 0 до 0 из 0 записей",
      "infoFiltered": "(отфильтровано из _MAX_ записей)",
      "infoPostFix": "",
      "loadingRecords": "Загрузка записей...",
      "zeroRecords": "Записи отсутствуют.",
      "emptyTable": "В таблице отсутствуют данные",
      "paginate": {
        "first": "Первая",
        "previous": "Предыдущая",
        "next": "Следующая",
        "last": "Последняя"
      },
      "aria": {
        "sortAscending": ": активировать для сортировки столбца по возрастанию",
        "sortDescending": ": активировать для сортировки столбца по убыванию"
      }
    }
  })

app/views/pages/help.html.haml
.row
  %h2=@page.title
  .col-md-12
    = @page.desc.html_safe

app/views/pages/index.html.haml
%h1 Page#index
%p Find me in app/views/page/index.html.haml

app/views/pages/payment.html.haml
.row
  %h2=@page.title
  .col-md-12
    = @page.desc.html_safe

app/views/pages/rule.html.haml
.row
  %h2=@page.title
  .col-md-12
    = @page.desc.html_safe

app/views/pages/show.html.haml
%h1 Page#show
%p Find me in app/views/page/show.html.haml

app/views/pages/user.html.haml
%h2
  .row
    .col-md-4
      %span.glyphicon.glyphicon-user
      #{@user.email.split('@')[0].gsub(/\b./, &:upcase)}
    - unless current_user.id == @user.id
      .col-md-8
        Начать диалог
%hr
.row
  .col-md-4
    .list-group
      %a.list-group-item{:href => "#"}
        %span.glyphicon.glyphicon-star
        Регистрация:
        %span.badge #{@user.created_at.strftime('%d.%m.%Y')}
      %a.list-group-item{:href => "#"}
        %span.glyphicon.glyphicon-user
        Посл. активность:
        %span.badge #{@user.updated_at.strftime('%d.%m.%Y')}
      -if @user.admin?
        %a.list-group-item{:href => "#"}
          %span.glyphicon.glyphicon-th-list
          Количество сделок:
          %span.badge ∞
      -elsif @user.seller?
        %a.list-group-item{:href => "#"}
          %span.glyphicon.glyphicon-th-list
          Количество сделок:
          %span.badge #{sender_account_sold @user.id}
        %a.list-group-item{:href => "#"}
          %span.glyphicon.glyphicon-th-list
          Количество аккаунтов:
          %span.badge #{sender_account_all @user.id}
      -else
        %a.list-group-item{:href => "#"}
          %span.glyphicon.glyphicon-th-list
          Количество сделок:
          %span.badge #{buyer_account @user.id}
  - unless current_user.id == @user.id
    .col-md-8
      - model_class = Conversation
      - @conversation = Conversation.new
      - @conversation.messages.build
      = render :partial => "conversations/form"