config/routes.rb
Rails.application.routes.draw do
  resources :conversations
  resources :accounts
  resources :products
  resources :coupons
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  mount Ckeditor::Engine => '/ckeditor'
  get '/rules',  to: 'pages#rule'
  get '/help',  to: 'pages#help'
  get '/payment',  to: 'pages#payment'
  get '/configuration',  to: 'pages#configuration'
  get '/users/balance', to: 'pages#balance'
  get '/account/pay',   to: 'accounts#pay'
  get '/users/:id',     to: 'pages#user'
  root to: 'products#index'
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :product
  belongs_to :buyer, class_name: "User", foreign_key:"buyer_id", optional: true
  belongs_to :seller, class_name: "User", foreign_key:"seller_id", optional: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]
  # load_and_authorize_resource
  # GET /accounts
  # GET /accounts.json
  def index
    if current_user.admin?
      @accounts = Account.all
    elsif current_user.seller?
      @accounts = Account.where(seller_id: current_user.id)
    elsif current_user.buyer?
      @accounts = Account.where(buyer_id: current_user.id)
    end
    @account = Account.new
  end

  def pay
    account = Account.find(params['id'])
    if current_user.balance >= account.price
      account.buyer_id = current_user.id
      account.save
      current_user.balance -= account.price
      current_user.save
      flash[:success] = "Аккаунт успешно куплен!"
      redirect_to '/accounts'
    else
      flash[:alert] = "На вашем счете недостаточно средств!"
      redirect_to params['url']
    end
  end
  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @accounts = Account.where(seller_id: current_user.id)
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to '/accounts', notice: 'Account was successfully created.' }
        format.json { render :index, status: :created, location: @account }
      else
        format.html { render :index }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    @account.seller_id = current_user.id
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to '/accounts', notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to '/accounts', notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:title, :email, :password, :seller_id, :buyer_id, :price, :product_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.haml
.panel-body
  = form_for @account do |f|
    .form-group
      %label Заголовок
      = f.text_field :title, class: "form-control"
    .form-group
      %label Email
      = f.text_field :email, class: "form-control"
    .form-group
      %label Пароль
      = f.text_field :password, class: "form-control"
    .form-group.hide
      = f.number_field :seller_id, value: "#{current_user.id}"
    .form-group
      %label Цена
      = f.text_field :price, class: "form-control"
    .form-group
      %label Игра
      = f.collection_select :product_id, Product.all, :id, :name, {prompt: "Выберите игру"}
    .actions
      = f.submit 'Добавить', class: 'btn btn-primary'
:javascript
  $( "#account_product_id" ).addClass("form-control")
  $( "span.selection" ).addClass("form-control")
  $( "#account_product_id" ).select2({
    theme: "bootstrap"
  });

app/views/accounts/edit.html.haml
%h1 Изменить аккаунт

= render 'form'

app/views/accounts/index.html.haml
-if current_user && (current_user.admin? || current_user.seller?)
  %h1 Добавить аккаунт
  = render 'form'


%h1 Мои аккаунты

%table#account.display.table.table-striped
  %thead
    %tr
      %th Игра
      %th Название
      %th Email
      %th Пароль
      %th Продавец
      %th Покупатель
      %th Цена
      - unless current_user.buyer?
        %th
        %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.product.name
        %td= account.title
        %td= account.email
        %td= account.password
        %td= link_to User.find_by(id: account.seller_id).email.split('@')[0].gsub(/\b./, &:upcase), "/users/#{account.seller_id}"
        %td
          -if account.buyer_id?
            = link_to User.find(account.buyer_id).email.split('@')[0].gsub(/\b./, &:upcase), "/users/#{account.buyer_id}"
        %td #{account.price.to_i} руб.
        - unless current_user.buyer?
          %td= link_to 'Изменить', edit_account_path(account)
          %td= link_to 'Удалить', account, method: :delete, data: { confirm: 'Are you sure?' }

:javascript
  $('#account').DataTable({
    "language":{
      "processing": "Подождите...",
      "search": "Поиск:",
      "lengthMenu": "Показать _MENU_ записей",
      "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
      "infoEmpty": "Записи с 0 до 0 из 0 записей",
      "infoFiltered": "(отфильтровано из _MAX_ записей)",
      "infoPostFix": "",
      "loadingRecords": "Загрузка записей...",
      "zeroRecords": "Записи отсутствуют.",
      "emptyTable": "В таблице отсутствуют данные",
      "paginate": {
        "first": "Первая",
        "previous": "Предыдущая",
        "next": "Следующая",
        "last": "Последняя"
      },
      "aria": {
        "sortAscending": ": активировать для сортировки столбца по возрастанию",
        "sortDescending": ": активировать для сортировки столбца по убыванию"
      }
    }
  })

app/views/accounts/new.html.haml
%h1 Добавить аккаунт
-if current_user && (current_user.admin? || current_user.seller?)
  = render 'form'


%h1 Мои аккаунты

%table#account.display.table.table-striped
  %thead
    %tr
      %th Email
      %th Пароль
      %th Продавец
      %th Покупатель
      %th Цена
      %th Игра
      - unless current_user.buyer?
        %th
        %th

  %tbody
    - @accounts.each do |account|
      %tr
        %td= account.email
        %td= account.password
        %td #{User.find_by(id: account.seller_id).email.split('@')[0].gsub(/\b./, &:upcase)}
        %td
          -if account.buyer_id?
            #{User.find(account.buyer_id).email.split('@')[0].gsub(/\b./, &:upcase)}
        %td #{account.price.to_i} руб.
        %td= account.product.name
        - unless current_user.buyer?
          %td= link_to 'Изменить', edit_account_path(account)
          %td= link_to 'Удалить', account, method: :delete, data: { confirm: 'Are you sure?' }

:javascript
  $('#account').DataTable({
    "language":{
      "processing": "Подождите...",
      "search": "Поиск:",
      "lengthMenu": "Показать _MENU_ записей",
      "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
      "infoEmpty": "Записи с 0 до 0 из 0 записей",
      "infoFiltered": "(отфильтровано из _MAX_ записей)",
      "infoPostFix": "",
      "loadingRecords": "Загрузка записей...",
      "zeroRecords": "Записи отсутствуют.",
      "emptyTable": "В таблице отсутствуют данные",
      "paginate": {
        "first": "Первая",
        "previous": "Предыдущая",
        "next": "Следующая",
        "last": "Последняя"
      },
      "aria": {
        "sortAscending": ": активировать для сортировки столбца по возрастанию",
        "sortDescending": ": активировать для сортировки столбца по убыванию"
      }
    }
  })

app/views/accounts/show.html.haml
%p#notice= notice

%p
  %b Email:
  = @account.email
%p
  %b Password:
  = @account.password
%p
  %b Seller:
  = @account.seller_id
%p
  %b Buyer:
  = @account.buyer_id
%p
  %b Price:
  = @account.price
%p
  %b Product:
  = @account.product

= link_to 'Edit', edit_account_path(@account)
\|
= link_to 'Back', accounts_path